Enable custom comment prefixes (fixes: #8)
BYK/connoisseur pull request #12
Opened 2017-07-08 17:38 UTC by onurtemizkan

2017-07-09 12:11 UTC, BYK requested changes
Good job. Just a few comments. Major concern is camelCase in CLI arguments.

2017-07-09 12:11 UTC, BYK commented on index.js
> +                .options({
Oh boy why so much indent? :(

2017-07-09 12:11 UTC, BYK commented on index.js
> +                        alias: "commentPrefix",
No camelCase in command line args. Should be `comment-prefix`. I may prefer `check-prefix` too.

2017-07-09 12:11 UTC, BYK commented on test/connoisseur.spec.js
> +        expect(connoisseur("", "STDIN", { commentPrefix: " → " })).to.be.empty();
I don't we should include spacing in the option.

2019-07-09 12:45 UTC, onurtemizkan commented
Updated PR 😇

2019-07-11 10:55 UTC, BYK approved these changes
Looks pretty good, thanks a lot!

2019-07-11 10:55 UTC, BYK commented on test/connoisseur.spec.js
> +        it("should print no error message for plain javascript ", done => {
```suggestion
        it("should print no error message for plain JavaScript", done => {
```

2019-07-11 10:55 UTC, BYK commented on test/connoisseur.spec.js
> +        it("should print no error message for a valid javascript source with a valid connoisseur test", done => {
```suggestion
        it("should print no error message for a valid JavaScript source with a valid connoisseur test", done => {
```

2019-07-11 10:55 UTC, BYK commented on test/connoisseur.spec.js
> +        it("should print errors for a valid javascript source with an invalid connoisseur test", done => {
```suggestion
        it("should print errors for a valid JavaScript source with an invalid connoisseur test", done => {
```

2019-07-11 10:55 UTC, BYK commented on test/connoisseur.spec.js
> +            expect(connoisseur("", "STDIN", { checkPrefix: "→" })).to.be.empty();
Shouldn't we have a default for this so the old API works without extra config?

2020-10-14 09:57 UTC, merged